config/routes.rb
Writ::Application.routes.draw do
  
  namespace :pen do
    
    resources :sessions, only: [ :new, :create, :destroy ]
    match '/login'  => 'sessions#new', as: :login
    match '/logout' => 'sessions#destroy', as: :logout
    
    resources :inquiries, only: [ :index, :update ]
    resources :pieces, only: [ :index, :create, :update ]
    
    root to: 'pieces#index'
    
  end
  
  resources :pieces, only: [ :index, :show ]
  resources :inquiries, only: [ :new, :create ]
  
  root to: 'public#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  
  # Attributes
  attr_accessible :name
  
  # Validations
  validates_presence_of :name
  
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
  
  # Scopes
  scope :most_recent, order('created_at desc')
  scope :replied, where('reply IS NOT NULL')
  scope :need_reply, where('reply IS NULL')
  
  # Attributes
  attr_accessible :email, :message, :name, :reply
  
  # Validations
  validates_presence_of :email, :message
  validates :email, email: true
  validates :reply, presence: true, on: :update
    
  # Class Methods
  def self.filter_by(params)
    if params[:replied]
      params[:replied] == 'true' ? replied : need_reply
    else
      scoped
    end
  end  
  
end

app/models/piece.rb
class Piece < ActiveRecord::Base
  
  # Gems
  mount_uploader :image, ImageUploader
  
  # Scopes
  default_scope order('created_at DESC')
  
  # Callbacks
  before_create :set_default_title
  
  # Attributes
  attr_accessible :description, :title, :image

  # Callback Methods
  def set_default_title
    self.title ||= File.basename(image.filename, '.*').titleize if image
  end
  
  # Instance Methods
  def next
    Piece.where("created_at < ?", self.created_at).first
  end
  
  def previous
    Piece.where("created_at > ?", self.created_at).last
  end
  
end

app/models/scribe.rb
class Scribe < ActiveRecord::Base
  
  # Gems 
  has_secure_password
  
  # Attributes
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation
  
  # Validations
  validates_presence_of :first_name, :last_name, :email, :password_confirmation
  validates :email, email: true, uniqueness: { case_sensitive: false }
  
  # Callbacks
  before_save :downcase_email

  # Callback Methods
  def downcase_email
    self.email = email.downcase
  end
  
  # Instance Methods
  def name
    first_name + ' ' + last_name
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :last_page_load
  
  def last_page_load
    session[:last_page_load] = Time.now
  end
  
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  
  def new
    @inquiry = Inquiry.new
  end
  
  def create
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.save
      InquiryMailer.notify_scribe(@inquiry).deliver
      flash[:success] = "Thanks for writing! I'll get back to you soon!"
      redirect_to root_path
    else
      render :new
    end
  end
  
end

app/controllers/pen/application_controller.rb
class Pen::ApplicationController < ApplicationController
  
  layout 'pen'
  
  before_filter :require_scribe!
  
  def sign_in scribe
    session[:scribe_id] = scribe.id
  end
  
  def current_scribe
    @current_scribe ||= Scribe.find(session[:scribe_id]) unless session[:scribe_id].nil?
  end
  helper_method :current_scribe
  
  private
    
    def require_scribe!
      reset_session unless session[:last_page_load].present? && session[:last_page_load] > 1.day.ago
      redirect_to pen_login_path, alert: "Please login to proceed." if current_scribe.nil?
    end
  
end

app/controllers/pen/inquiries_controller.rb
class Pen::InquiriesController < Pen::ApplicationController
  
  def index
    @inquiries = Inquiry.filter_by(params).most_recent.page(params[:page]).per(5)
  end
  
  def update
    @inquiries = Inquiry.most_recent.page(params[:page]).per(5)
    @inquiry = Inquiry.find(params[:id])
    if @inquiry.update_attributes(params[:inquiry])
      InquiryMailer.reply_to(@inquiry).deliver
    end
  end
  
end

app/controllers/pen/pieces_controller.rb
class Pen::PiecesController < Pen::ApplicationController
  
  def index
    @pieces = Piece.all
  end
  
  def create
    @piece = Piece.create(params[:piece])
  end
  
  def update
    @piece = Piece.find(params[:id])
    @piece.update_attributes(params[:piece])
    respond_to do |format|
      format.js { render :layout => false }
    end
  end

end

app/controllers/pen/sessions_controller.rb
class Pen::SessionsController < Pen::ApplicationController
  
  skip_before_filter :require_scribe!
  
  def new
  end

  def create
    scribe = Scribe.find_by_email params[:email]
    if scribe && scribe.authenticate(params[:password])
      sign_in scribe
      redirect_to pen_root_path, notice: "Logged in!"
    else
      flash.now.alert = "Invalid login credentials."
      render :new
    end
  end

  def destroy
    session[:scribe_id] = nil
    flash[:notice] = "Logged out."
    redirect_to root_path
  end
  
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  
  def index
    @pieces = Piece.all
    @piece = Piece.first
  end
  
  def show
    @pieces = Piece.all
    @piece = Piece.find(params[:id])
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  
  def index
    @pieces = Piece.all
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def pretty_date(date)
    date.strftime('%B %e, %Y @ %l:%M %p') if date.present?
  end
  
end

app/views/inquiries/new.html.haml
.inquiries
  .new
    .buffer
      %h1 Contact Emily
    .ribbon.blue.thin
    
    .third.grid
      
      .column.double
        .buffer.top.left
          .grey.wrapper.left-text
            %h2 Consultation
            %p 
              Whether you're looking for custom calligraphy
              or font work, drop me a line.
            %p
            = render 'shared/form_errors', item: @inquiry
            = form_for @inquiry do |f|
              = f.label :name, 'Name:'
              = f.text_field :name
              = f.label :email, 'E-mail Address:'
              = f.text_field :email
              = f.label :message, 'Message:'
              = f.text_area :message
              = f.submit "SEND", class: 'submit pull-right'
              .clear
      
      .column
        .buffer.top.right
          .grey.wrapper.left-text
            %h2 Contact
            %table
              %body
                %tr
                  %td.left Email:
                  %td.right= mail_to 'emily@fixitwithcode.com', 'emily@fixitwithcode.com'
                %tr
                  %td.left Phone:
                  %td.right= link_to '(872) 216-8247', "tel:#{18722168247}"
                %tr
                  %td.left Residence:
                  %td.right New York, NY
                  
            
            %h3 Profiles
            .pull-left
              = link_to image_tag('twitter.png', class: 'no-frills', size: '50x50'), 'http://www.twitter.com/emilyellison986'
              = link_to image_tag('linkedin.png', class: 'no-frills', size: '50x50'), 'http://www.linkedin.com/in/emilyellison986'
              = link_to image_tag('github.png', class: 'no-frills', size: '50x50'), 'http://www.github.com/emilyellison986'
            .clear
      .clear
      

app/views/layouts/application.html.haml
!!! html5
%html
  %head
    %title Writ
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{ href: 'http://fonts.googleapis.com/css?family=Sofia', rel: 'stylesheet', type: 'text/css' }
    %link{ href: 'http://fonts.googleapis.com/css?family=Quando', rel: 'stylesheet', type: 'text/css' }    
    
  %body
    - [:success, :notice, :error, :alert].each do |type|        
      - if flash[type].present?
        %div{ class: "flash #{type}" }
          .container= flash[type]

    %header
      .container
        = link_to "WRIT", root_path, class: 'brand'
        %ul
          %li= link_to "Gallery", pieces_path, class: "#{'active' if params[:controller] == 'pieces'}"
          %li= link_to "Contact", new_inquiry_path, class: "#{'active' if params[:controller] == 'inquiries'}"
        .clear
          
    .container
      .content        
        = yield
    
    %footer
      .container
        %ul.pull-left
          %li 
            Web Development and Design by 
            = link_to 'Fix It With Code', 'http://www.fixitwithcode.com', class: 'fix-it-with-code'
            
        %ul.pull-right
          %li
            %iframe{ src: 'http://ghbtns.com/github-btn.html?user=emilyellison986&type=follow', allowtransparency: 'true', frameborder: 0, scrolling: 0, width: 160, height: 20 }
          %li= link_to 'Follow @emilyellison986', 'https://twitter.com/emilyellison986', class: 'twitter-follow-button', 'data-show-count' => 'false', 'data-show-screen-name' => 'false'
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>     
        .clear

app/views/layouts/pen.html.haml
!!! html5
%html
  %head
    %title Writ
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{ href: 'http://fonts.googleapis.com/css?family=Sofia', rel: 'stylesheet', type: 'text/css' }
    %link{ href: 'http://fonts.googleapis.com/css?family=Quando', rel: 'stylesheet', type: 'text/css' }    
    
  %body
    - [:success, :notice, :error, :alert].each do |type|        
      - if flash[type].present?
        %div{ class: "flash #{type}" }
          .container= flash[type]

    %header
      .container
      
        - if current_scribe
          = link_to "WRIT", root_path, class: 'brand'
          %ul
            %li= link_to "Pieces", pen_pieces_path
            %li= link_to "Messages", pen_inquiries_path
            %li= link_to "Log Out", pen_logout_path
          .clear
            
        - else
          = link_to "WRIT", root_path, class: 'brand'
          .clear
          
    .container
      .content        
        = yield

app/views/pen/inquiries/_inquiry.html.haml
.grey.wrapper{ id: dom_id(inquiry), class: 'inquiry' }
  .buffer.small.thin
    .pull-left
      = inquiry.name
      <
      = mail_to inquiry.email, inquiry.email
      >
    .pull-right= inquiry.reply? ? 'Replied' : link_to('Reply', '#', class: 'reply').html_safe
    .clear

  %p= inquiry.message
  %p= pretty_date inquiry.created_at

  - if inquiry.reply?

    %br
    .buffer.small.thin
      .pull-left
        Emily Ellison
        <
        = mail_to 'emily@fixitwithcode.com', 'emily@fixitwithcode.com'
        >
      .clear
    %p= inquiry.reply
    %p= pretty_date inquiry.updated_at

  - else
  
    = form_for [ :pen, inquiry ], html: { class: 'full' }, remote: true do |f|
      = f.text_area :reply
      = f.submit 'SEND', class: 'submit pull-right'
      .clear

app/views/pen/inquiries/index.html.haml
.pen
  .inquiries
    .index
      .buffer
        %h1 Messages
      .thin.blue.ribbon
      
      .quarter.grid
        .column
          
          .buffer.top.left
            %ul.sub-nav
              %li= link_to 'All Messages', pen_inquiries_path, class: "grey wrapper small #{ 'active' if params[:replied].nil? }"
              %li= link_to 'Need Reply', pen_inquiries_path(replied: false), class: "grey wrapper small #{ 'active' if params[:replied] == 'false' }"
              %li= link_to 'Replied', pen_inquiries_path(replied: true), class: "grey wrapper small #{ 'active' if params[:replied] == 'true' }"
        
        .triple.column
      
          .buffer.top.right
            - @inquiries.each do |inquiry|
              = render 'inquiry', inquiry: inquiry
        
            = paginate @inquiries
            
        .clear

app/views/pen/inquiries/update.js.erb
<% if @inquiry.errors.present? %>
  $('.submit').val('SEND');
  alert("Failed to send reply: <%= j @inquiry.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#<%= dom_id(@inquiry) %>").fadeOut(0, function() {
    $(this).replaceWith("<%= j render(@inquiry) %>");
    $("#edit_<%= dom_id(@inquiry) %>").hide();
    $(this).fadeIn(500);
  });
<% end %>

app/views/pen/pieces/_piece.html.haml
.piece.pull-left{ id: dom_id(piece) }
  .grey.small.wrapper  
    = image_tag piece.image_url(:large), size: '245x170'
    = form_for [ :pen, piece ], html: { class: 'small' }, remote: true do |f|
      = f.text_field :title, placeholder: 'Title'
      = f.text_area :description, placeholder: 'Description'
      = f.submit "SAVE", class: 'submit pull-right'
      .clear

app/views/pen/pieces/create.js.erb
<% if @piece.new_record? %>
  alert("Failed to upload piece: <%= j @piece.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $('.no_pieces').remove();
  $("#pieces").prepend("<%= j render(@piece) %>");
<% end %>

app/views/pen/pieces/index.html.haml
.pen
  .pieces
    .index      
      .buffer
        %h1 Pieces
        
      .thin.blue.ribbon
      
      .quarter.grid

        .column
          .buffer.top.left
            %ul.sub-nav
              %li= link_to 'All Pieces', '#', class: 'grey short wrapper active'
          
            .grey.small.wrapper
              %h4 Add Pieces
              %p.center
                Drag and drop photos
              = render 'shared/form_errors', item: @piece
              = form_for [ :pen, Piece.new ] do |f|
                = f.file_field :image, multiple: true, name: "piece[image]", class: "#{'file_field' if !Rails.env.test? }"
              
              %script{ id: "template-upload", type: "text/x-tmpl" }
                .upload
                  {%=o.name%}
                  .progress
                    .bar
        
        .triple.column
          .buffer.top.right
            #pieces
              - if @pieces.empty?
                .no_pieces
                  %p You haven't added any pieces yet.
                  %p 
                    To add a piece, you can click "Choose File" and select a file,
                    or simply drag and drop a photo of it from your computer.
              - @pieces.each do |piece|
                = render "piece", piece: piece
        
                    
        .clear

app/views/pen/pieces/update.js.erb
$("#<%= dom_id(@piece) %>").fadeOut(0, function() {
  $(this).html("<%= j render(@piece) %>");
  $(this).fadeIn(500);
});

app/views/pieces/_pieces.html.haml
.buffer
  %h1 Gallery

.thin.blue.ribbon

.third.grid

  .double.column
    .buffer.top.left
      = image_tag(@piece.image_url, class: 'large', id: dom_id(@piece))
                
      .buffer.medium
        - if @piece.previous.present?
          .pull-left= link_to '&larr; Previous'.html_safe, piece_path(@piece.previous), class: 'btn', id: 'previous'
        - if @piece.next.present?
          .pull-right= link_to 'Next &rarr;'.html_safe, piece_path(@piece.next), class: 'btn', id: 'next'
        .clear
      
  .column
    .buffer.top.right
      - @pieces.each do |piece|
        = link_to image_tag(piece.image_url, class: 'thumb pull-left'), piece_path(piece)
  
  .clear

app/views/pieces/index.html.haml
.pieces
  .index
    .buffer
      %h1 Gallery
    .thin.blue.ribbon
    .third.grid
    
      .double.column
        .buffer.top.left
          = image_tag(@pieces.first.image_url, class: 'large')
          
      .column
        .buffer.top.right
          - @pieces.each do |piece|
            = image_tag(piece.image_url, class: 'thumb pull-left')

app/views/pieces/show.html.haml
.pieces
  .show
    = render 'pieces/pieces'

app/views/shared/_form_errors.html.haml
- if item && item.errors.any?
  .form-errors
    %p Whoops! Something went wrong.
    %ul
      - item.errors.full_messages.each do |msg|
        %li= msg